### PR TITLE
Specified Pip and Python Commands

### PR DESCRIPTION
**Pull request by rusmelezi**
I specified Pip and Python commands to prevent bugs when there is another installed Python3 version on system.

### CODE REVIEW

**Comment by NovaCygni** [comment]
Python 3 is Python3, there should be no way any confusion can happen unless someone has a massively broken set of Python installs as it is... :/ Only 2 python versions need distinction, Py2 and then Py3, if the user has a "Multiple" of each installed they should correct the installs.

**Comment by rusmelezi** [comment]
When i installed 3.5.2 and 3.6.2 on my system v3n0m doesn't work if i won't
do these changes.

**Comment by NovaCygni** [comment]
What system OS?

**Comment by rusmelezi** [comment]
Kali Linux and KDE Neon, on both of this operation systems i am getting
error when i installed Python 3.5.2 and 3.6.2 on my system together, so i
am doing these changes to use v3n0m suit.  Why don't you just accept my
pull request ? Is there any harmful thing about specifying Python versions
on commands ? This is prevent bugs kind of happened to me.

**Comment by NovaCygni** [comment]
Was just unsure why you wouldnt just have Python 3.6 running as the system default for Python3, Is there any specific reason your keeping a older version of Python3 on the system? Technically all im doing is ensuring people have a correct Python setup, but, no reason to not accept merge though so might aswell.

**Pull request merged**
